version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"  # Пробрасываем порт 3000
    volumes:
      - .:/usr/src/app
    command: npm start